-
  name: Copy file to target servers
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Copy file
      copy:
        src: /home/{{ username }}/test/test-file.txt
        dest: /tmp/test-file.txt
