-
  name: Create ffile on target servers
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure the test directory exists
      file:
        path: /tmp/test
        state: directory
    - name: Ensure test-file.txt exists
      lineinfile:
        path: /tmp/test/test-file.txt
        line: Hello! This is a test.
        create: yes
